// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TareasDLL.Models;

public partial class AuditoriaTarea
{
    public int AuditoriaId { get; set; }

    public int TareaId { get; set; }

    public int UsuarioId { get; set; }

    public string EstatusAnterior { get; set; }

    public string EstatusNuevo { get; set; }

    public DateTime FechaCambio { get; set; }
}