// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace TareasDLL.Models
{
    public partial class SP_GetPendingTasksResult
    {
        public string Usuario { get; set; }
        public int? TotalPendientes { get; set; }
        public int? TotalVencidas { get; set; }
    }
}
