// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TareasDLL.Models;

public partial class Tarea
{
    public int TareaId { get; set; }

    public string Titulo { get; set; } = string.Empty;

    public string Descripcion { get; set; } = string.Empty;

    public string Prioridad { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public DateTime? FechaInicio { get; set; }

    public DateTime? FechaFinalizacion { get; set; }

    public DateTime? FechaLimite { get; set; }

    public string Estatus { get; set; }

    public int UsuarioId { get; set; }

    public virtual Usuario Usuario { get; set; }
}