// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TareasDLL.Models;

public partial class Usuario
{
    public int UsuarioId { get; set; }

    public string Nombre { get; set; }

    public string Correo { get; set; }

    public virtual ICollection<Tarea> Tareas { get; set; } = new List<Tarea>();
}