// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using TareasDLL.Models;

namespace TareasDLL.Context
{
    public partial class DB_AppDbContext
    {
        private IDB_AppDbContextProcedures _procedures;

        public virtual IDB_AppDbContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new DB_AppDbContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IDB_AppDbContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<SP_GetPendingTasksResult>().HasNoKey().ToView(null);
        }
    }

    public partial class DB_AppDbContextProcedures : IDB_AppDbContextProcedures
    {
        private readonly DB_AppDbContext _context;

        public DB_AppDbContextProcedures(DB_AppDbContext context)
        {
            _context = context;
        }

        public virtual async Task<List<SP_GetPendingTasksResult>> SP_GetPendingTasksAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_GetPendingTasksResult>("EXEC @returnValue = [dbo].[SP_GetPendingTasks]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
