// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using TareasDLL.Models;

namespace TareasDLL.Context;

public partial class DB_AppDbContext : DbContext
{
    public DB_AppDbContext(DbContextOptions<DB_AppDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AuditoriaTarea> AuditoriaTareas { get; set; }

    public virtual DbSet<Tarea> Tareas { get; set; }

    public virtual DbSet<Usuario> Usuarios { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AuditoriaTarea>(entity =>
        {
            entity.HasKey(e => e.AuditoriaId).HasName("PK__Auditori__095694C3B6F919C8");

            entity.Property(e => e.EstatusAnterior)
                .IsRequired()
                .HasMaxLength(15);
            entity.Property(e => e.EstatusNuevo)
                .IsRequired()
                .HasMaxLength(15);
            entity.Property(e => e.FechaCambio)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<Tarea>(entity =>
        {
            entity.HasKey(e => e.TareaId).HasName("PK__Tareas__5CD83991B4E496A1");

            entity.ToTable(tb => tb.HasTrigger("trg_Tareas_Estatus_Auditoria"));

            entity.HasIndex(e => e.Estatus, "IX_Tareas_Estatus");

            entity.HasIndex(e => e.FechaCreacion, "IX_Tareas_FechaCreacion");

            entity.HasIndex(e => e.Prioridad, "IX_Tareas_Prioridad");

            entity.HasIndex(e => e.UsuarioId, "IX_Tareas_UsuarioId");

            entity.Property(e => e.Estatus)
                .IsRequired()
                .HasMaxLength(15);
            entity.Property(e => e.FechaCreacion)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.FechaFinalizacion).HasColumnType("datetime");
            entity.Property(e => e.FechaInicio).HasColumnType("datetime");
            entity.Property(e => e.FechaLimite).HasColumnType("datetime");
            entity.Property(e => e.Prioridad)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.Titulo)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.Usuario).WithMany(p => p.Tareas)
                .HasForeignKey(d => d.UsuarioId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Tareas_Usuarios");
        });
        modelBuilder.Entity<Tarea>()
            .Property(t => t.FechaCreacion)
            .Metadata.SetAfterSaveBehavior(
                Microsoft.EntityFrameworkCore.Metadata.PropertySaveBehavior.Ignore
            );

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.HasKey(e => e.UsuarioId).HasName("PK__Usuarios__2B3DE7B8B6741DC2");

            entity.HasIndex(e => e.Correo, "UQ__Usuarios__60695A19422B450F").IsUnique();

            entity.Property(e => e.Correo)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100);
        });

        OnModelCreatingGeneratedProcedures(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}