// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using TareasDLL.Models;

namespace TareasDLL.Context
{
    public partial interface IDB_AppDbContextProcedures
    {
        Task<List<SP_GetPendingTasksResult>> SP_GetPendingTasksAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
